public class Sub_Constant {
    
    public static final String ELEMENTS_MANQUANTS = 'Éléments manquants';
    public static final String IMMO_NEUF = 'Conformité Immo neuf';
    public static final String PUB = 'Conformité Pub';
    public static final String IMMO_NEUF_MISSING = 'PromoterDescription__c#FlowType__c#ProductWorkflow__c#ContractEmail__c#CompanySiret__c#CompanyName__c#CompanyAddressStreet__c#CompanyAddressZipcode__c#CompanyAddressCity__c#CompanyPhone__c#ContactGender__c#ContactFirstName__c#ContactLastName__c#LeadPhone__c';
   	public static final String PUB_MISSING = 'EffectiveEndDate__c';	

}